/**
 * Brandi canvas layer: emit and validate Design Component artboards for
 * Claude Code's `/design` canvas.
 *
 * The division of labour here is deliberate.
 *
 *   Generated by code   the artboards that are SPECIFICATIONS: the palette
 *                       sheet, the type specimen, the component states, the
 *                       token sheet. These have to be exactly right, and a
 *                       machine is better at exactly right than a model is.
 *
 *   Authored by Claude  the artboards that are DESIGN: direction sketches, the
 *                       landing page, the app screen, the poster, the slide.
 *                       Generating those from a template is precisely how a
 *                       brand ends up looking like every other brand.
 *
 * Everything in this file targets the `.dc.html` format the canvas consumes.
 * The format fails silently in several places (a missing image renders as a
 * broken image with no warning; an expression inside a handlebars hole renders
 * as literal text), so `validateArtboard` exists to turn those silent failures
 * into loud ones before anything is published.
 */

const SUPPORT_LINE = '<script src="./support.js"></script>';

/** Frame sizes the canvas and the real world agree on. */
export const FRAMES = Object.freeze({
  phone: { w: 390, h: 844, note: 'iPhone logical resolution' },
  phoneLarge: { w: 430, h: 932 },
  tablet: { w: 834, h: 1112 },
  desktop: { w: 1440, h: 900 },
  desktopTall: { w: 1440, h: 1600 },
  slide: { w: 1920, h: 1080, note: '16:9. Body type never below 24px at this size' },
  socialSquare: { w: 1080, h: 1080 },
  socialStory: { w: 1080, h: 1920 },
  socialWide: { w: 1200, h: 630, note: 'Open Graph card' },
  // Print, authored at 96 px per inch, which is what the canvas exports at.
  a4: { w: 794, h: 1123, note: 'A4 portrait at 96ppi' },
  a4Landscape: { w: 1123, h: 794 },
  a5: { w: 559, h: 794 },
  letter: { w: 816, h: 1056 },
  businessCard: { w: 336, h: 192, note: '89 x 51 mm at 96ppi' },
  // Physical surfaces. A word-of-mouth business meets its customers on these
  // long before it meets them on a home page, and the proof set said otherwise
  // while the intake said this. Authored at 96ppi like the print frames, at a
  // scale that keeps the file workable rather than at full size.
  signage: { w: 1200, h: 400, note: 'A shopfront band at 1:10. State the real width in mm on the artboard' },
  aFrame: { w: 600, h: 900, note: 'A-frame or sandwich board, 2:3' },
  vehicle: { w: 1400, h: 600, note: 'A van side at 1:10. The door and wheel arch are where artwork dies' },
  garment: { w: 400, h: 400, note: 'An embroidered chest mark, at the size it is actually stitched' },
  sticker: { w: 400, h: 400, note: 'A die-cut sticker or a window decal' },
  sheet: { w: 1200, h: 1600, note: 'A specification sheet. Not a real-world size' },
});

/**
 * Typefaces that make a design look machine-generated on sight. The canvas
 * loads fonts from Google Fonts only, so the replacements named here are all
 * available from that one host.
 */
import { loadContractSync, slopFindings } from './slop.mjs';

// The marker every generated artefact carries in its head. Duplicated as a
// string rather than imported from guardian.mjs, which imports this module.
const GENERATED_MARKER = 'generated from the resolved system';

/**
 * Views of the contract rather than second lists to maintain. The document at
 * references/04-anti-slop.md is where a face gets banned.
 *
 * The two stay separate because the contract separates them, and folding them
 * together turned "Instrument Serif is a default you should argue for" into
 * "Instrument Serif is forbidden", which is a different and wrong claim.
 * A ban is a p0 and takes a waiver; a default is a p1 and takes a reason.
 */
export const BANNED_FONTS = Object.freeze([...loadContractSync().banned_fonts.literals]);
export const DEFAULT_FONTS = Object.freeze([...(loadContractSync().banned_fonts.soft_literals ?? [])]);

const EMOJI_RE = /\p{Extended_Pictographic}/u;

// ---------------------------------------------------------------------------
// Emitting
// ---------------------------------------------------------------------------

const escapeAttr = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');

/** Escape a JSON object for a single-quoted `data-props` attribute. */
export function encodeProps(obj) {
  // The runtime reads the attribute with getAttribute, so HTML entities decode
  // first and THEN it is JSON-parsed. Only three characters need escaping;
  // raw UTF-8 passes through untouched.
  return JSON.stringify(obj).replace(/&/g, '&amp;').replace(/'/g, '&#39;');
}

/** Decode a `data-props` attribute back to an object. */
export function decodeProps(attr) {
  return JSON.parse(String(attr).replace(/&#39;/g, "'").replace(/&quot;/g, '"').replace(/&amp;/g, '&'));
}

/**
 * Build one `.dc.html` artboard.
 *
 * @param {object} spec
 * @param {string} spec.name      artboard name, without the extension. PascalCase.
 * @param {string} spec.body      the markup inside <x-dc>. Required.
 * @param {string} [spec.css]     CSS for the <helmet><style> block.
 * @param {string} [spec.fonts]   a Google Fonts stylesheet URL, or several.
 * @param {object} [spec.props]   data-props. Omit for a static artboard.
 * @param {string} [spec.logic]   the body of the Component class. Omit for static.
 * @param {{width:number,height:number}} [spec.preview]
 * @param {string} [spec.systemNote]  the mini-system comment. Strongly encouraged.
 */
export function artboard(spec) {
  const { name, body, css = '', fonts, props, logic, preview, systemNote } = spec;
  if (!name || !/^[A-Z][A-Za-z0-9]*$/.test(name)) {
    throw new TypeError(`artboard name must be PascalCase with no extension, got ${JSON.stringify(name)}`);
  }
  if (!body || !body.trim()) throw new TypeError(`artboard ${name} has no body`);

  const fontLinks = (Array.isArray(fonts) ? fonts : fonts ? [fonts] : [])
    .map((href) => {
      if (!/^https:\/\/fonts\.googleapis\.com\//.test(href)) {
        throw new RangeError(
          `The canvas can only load fonts from fonts.googleapis.com. Got ${href}. ` +
            'Embed anything else as a @font-face data: URI inside the artboard.',
        );
      }
      return `    <link rel="stylesheet" href="${escapeAttr(href)}">`;
    })
    .join('\n');

  // $preview is a component-level size hint that lives in data-props, so a
  // preview with no other props still needs the attribute. Missing this meant
  // the hint was silently dropped.
  const propsPayload = { ...(props ?? {}), ...(preview ? { $preview: preview } : {}) };
  const propsAttr = Object.keys(propsPayload).length ? ` data-props='${encodeProps(propsPayload)}'` : '';
  const needsScript = Boolean(props || logic || preview);

  const parts = [];
  parts.push('<!doctype html>');
  parts.push('<html>');
  parts.push('<head>');
  parts.push('  <meta charset="utf-8">');
  parts.push(`  ${SUPPORT_LINE}`);
  parts.push('</head>');
  parts.push('<body>');
  if (systemNote) {
    parts.push('<!--');
    for (const line of String(systemNote).trim().split('\n')) {
      parts.push(`  ${line.replace(/--/g, '- -')}`);
    }
    parts.push('-->');
  }
  parts.push('<x-dc>');
  parts.push('<helmet>');
  if (fontLinks) parts.push(fontLinks);
  parts.push('  <style>');
  parts.push(indent(baseCss() + '\n' + css, 4));
  parts.push('  </style>');
  parts.push('</helmet>');
  parts.push(body.trim());
  parts.push('</x-dc>');
  if (needsScript) {
    parts.push(`<script data-dc-script${propsAttr}>`);
    parts.push('class Component extends DCLogic {');
    parts.push(indent(logic ?? '', 2));
    parts.push('}');
    parts.push('</script>');
  }
  parts.push('</body>');
  parts.push('</html>');
  parts.push('');
  return parts.join('\n');
}

function indent(text, n) {
  const pad = ' '.repeat(n);
  return String(text)
    .split('\n')
    .map((l) => (l.trim() ? pad + l : l))
    .join('\n');
}

/**
 * The floor every artboard sits on. Deliberately tiny: it resets the things
 * that bite (default margin, browser-blue links, images overflowing their
 * frame) and decides nothing else.
 */
function baseCss() {
  return `* { box-sizing: border-box; }
body { margin: 0; }
img, svg { max-width: 100%; }
a { color: inherit; text-decoration-thickness: 0.06em; text-underline-offset: 0.18em; }
a:hover { text-decoration-thickness: 0.12em; }`;
}

// ---------------------------------------------------------------------------
// canvas.json
// ---------------------------------------------------------------------------

/**
 * Lay artboards out in rows and emit a canvas.json manifest.
 *
 * Gaps are not cosmetic: the canvas draws a name strip and tweak chips above
 * each frame, so frames closer than 80px in a row (or 120px between rows)
 * collide with each other's chrome.
 */
export function canvasManifest(entries, {
  columns = 3,
  gapX = 120,
  gapY = 200,
  originX = 0,
  originY = 0,
  pages,
  annotations,
  launch,
} = {}) {
  if (!entries.length) throw new TypeError('a canvas needs at least one artboard');

  const seen = new Set();
  for (const e of entries) {
    if (!e || typeof e.file !== 'string') throw new TypeError('every artboard entry needs a file name');
    const stem = e.file.replace(/\.dc\.html$/, '').toLowerCase();
    if (seen.has(stem)) throw new RangeError(`duplicate artboard name: ${e.file}`);
    seen.add(stem);
    if (!/\.dc\.html$/.test(e.file)) throw new RangeError(`artboard files must end in .dc.html, got ${e.file}`);
    // One missing width used to make x NaN for every artboard after it, which
    // JSON writes as null and the overlap check cannot see, so a broken layout
    // shipped silently to the seeder.
    for (const [k, required] of [['w', true], ['h', true], ['x', false], ['y', false]]) {
      const v = e[k];
      if (v === undefined && !required) continue;
      if (typeof v !== 'number' || !Number.isFinite(v)) {
        throw new TypeError(`${e.file}: ${k} must be a finite number, got ${JSON.stringify(v)}`);
      }
      if ((k === 'w' || k === 'h') && v <= 0) {
        throw new RangeError(`${e.file}: ${k} must be positive, got ${v}`);
      }
    }
  }

  // Lay out each page independently.
  //
  // A canvas shows one page at a time, so a single cursor running across every
  // artboard is wrong: page A takes positions 1 and 2, page B takes 3 and 4,
  // and each page then renders with the other's slots left as holes. The result
  // is a canvas that looks half-empty and scattered, which is exactly what it
  // was. Each page gets its own cursor, starting at the origin.
  const placed = [];
  const pageOf = (e) => e.page ?? '\u0000default';
  const order = [...new Set(entries.map(pageOf))];

  for (const pageId of order) {
    let x = originX;
    let y = originY;
    let rowHeight = 0;
    let col = 0;
    for (const e of entries.filter((entry) => pageOf(entry) === pageId)) {
      // An explicitly positioned artboard keeps its place and does not move the
      // cursor: it was put there on purpose.
      const explicit = Number.isFinite(e.x) && Number.isFinite(e.y);
      if (!explicit && col >= columns) {
        x = originX;
        y += rowHeight + gapY;
        rowHeight = 0;
        col = 0;
      }
      placed.push({
        file: e.file,
        x: Math.round(explicit ? e.x : x),
        y: Math.round(explicit ? e.y : y),
        w: e.w,
        h: e.h,
        ...(e.title ? { title: e.title } : {}),
        ...(e.expand ? { expand: e.expand } : {}),
        ...(e.print ? { print: e.print } : {}),
        ...(e.page ? { page: e.page } : {}),
        ...(e.is_interactive ? { is_interactive: true } : {}),
      });
      if (!explicit) {
        x += e.w + gapX;
        rowHeight = Math.max(rowHeight, e.h);
        col++;
      }
    }
  }

  const manifest = { artboards: placed };
  if (annotations?.length) {
    const ids = new Set();
    for (const a of annotations) {
      if (!/^[A-Za-z0-9_-]{1,40}$/.test(a.id)) throw new RangeError(`bad annotation id: ${a.id}`);
      if (ids.has(a.id)) throw new RangeError(`duplicate annotation id: ${a.id}`);
      ids.add(a.id);
      if (typeof a.text !== 'string') throw new TypeError(`annotation ${a.id} text must be one plain string`);
      if (a.w < 120 || a.w > 2000) throw new RangeError(`annotation ${a.id} width must be 120-2000`);
    }
    manifest.annotations = annotations.map((a) => ({
      id: a.id, x: Math.round(a.x), y: Math.round(a.y), w: Math.round(a.w), text: a.text,
      ...(a.page ? { page: a.page } : {}),
    }));
  }
  if (pages?.length) {
    if (pages.length > 40) throw new RangeError('a canvas may have at most 40 pages');
    const pageIds = new Set(pages.map((p) => p.id));
    for (const p of pages) {
      if (!p.name) throw new TypeError(`page ${p.id} needs a name`);
      if (!/^[A-Za-z0-9_-]{1,40}$/.test(p.id)) throw new RangeError(`bad page id: ${p.id}`);
    }
    for (const a of placed) {
      if (a.page && !pageIds.has(a.page)) throw new RangeError(`${a.file} is on unlisted page ${a.page}`);
    }
    manifest.pages = pages.map((p) => ({ id: p.id, name: p.name }));
  }
  if (launch) {
    if (launch.view === 'focused') {
      if (!placed.some((a) => a.file === launch.file)) {
        throw new RangeError(`launch targets ${launch.file}, which is not on the canvas`);
      }
      manifest.launch = { view: 'focused', file: launch.file };
    } else if (launch.view === 'canvas') {
      if (launch.page && !manifest.pages?.some((p) => p.id === launch.page)) {
        throw new RangeError(`launch targets unlisted page ${launch.page}`);
      }
      manifest.launch = { view: 'canvas', ...(launch.page ? { page: launch.page } : {}) };
    } else {
      throw new RangeError(`launch.view must be "canvas" or "focused", got ${launch.view}`);
    }
  }
  return manifest;
}

/**
 * Frames that do not overlap but sit too close for the canvas chrome.
 *
 * The recipe promises this is checked, so it is checked. A name strip and a row
 * of tweak chips sit above every frame; below about 120px of vertical gap they
 * start crowding the frame above, and side by side under 80px the titles run
 * together. Neither clips content, so these are warnings rather than errors.
 */
export function findCrowding(manifest, { minX = 80, minY = 120 } = {}) {
  const tight = [];
  const boards = manifest.artboards;
  for (let i = 0; i < boards.length; i++) {
    for (let j = i + 1; j < boards.length; j++) {
      const a = boards[i];
      const b = boards[j];
      if ((a.page ?? null) !== (b.page ?? null)) continue;
      const overlapY = a.y < b.y + b.h && b.y < a.y + a.h;
      const overlapX = a.x < b.x + b.w && b.x < a.x + a.w;
      if (overlapY) {
        const gapX = a.x < b.x ? b.x - (a.x + a.w) : a.x - (b.x + b.w);
        if (gapX >= 0 && gapX < minX) tight.push({ a: a.file, b: b.file, axis: 'x', gap: Math.round(gapX), min: minX });
      }
      if (overlapX) {
        const gapY = a.y < b.y ? b.y - (a.y + a.h) : a.y - (b.y + b.h);
        if (gapY >= 0 && gapY < minY) tight.push({ a: a.file, b: b.file, axis: 'y', gap: Math.round(gapY), min: minY });
      }
    }
  }
  return tight;
}

/** Do any two frames on the same page overlap, chrome included? */
export function findOverlaps(manifest, { chromeTop = 56 } = {}) {
  const clashes = [];
  const boards = manifest.artboards;
  for (let i = 0; i < boards.length; i++) {
    for (let j = i + 1; j < boards.length; j++) {
      const a = boards[i];
      const b = boards[j];
      if ((a.page ?? null) !== (b.page ?? null)) continue;
      const ax1 = a.x; const ax2 = a.x + a.w;
      const ay1 = a.y - chromeTop; const ay2 = a.y + a.h;
      const bx1 = b.x; const bx2 = b.x + b.w;
      const by1 = b.y - chromeTop; const by2 = b.y + b.h;
      if (ax1 < bx2 && bx1 < ax2 && ay1 < by2 && by1 < ay2) {
        clashes.push({ a: a.file, b: b.file });
      }
    }
  }
  return clashes;
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/**
 * Check an artboard against the parts of the format that fail silently, and
 * against the house rules that keep output from looking machine-made.
 *
 * Returns `{ok, errors, warnings}`. Errors mean the artboard will not render
 * correctly. Warnings mean it will render, and look generic.
 */
export function validateArtboard(source, { name = 'artboard', allowFonts = true } = {}) {
  const errors = [];
  const warnings = [];
  const err = (m, fix) => errors.push({ message: m, fix });
  const warn = (m, fix) => warnings.push({ message: m, fix });

  // --- Structure ---------------------------------------------------------
  if (!source.includes(SUPPORT_LINE)) {
    err(
      'The support.js head line is missing or altered.',
      `Include exactly: ${SUPPORT_LINE}. The editor swaps it for the inline runtime at render time.`,
    );
  }
  if (!/<x-dc>/.test(source) || !/<\/x-dc>/.test(source)) {
    err('No <x-dc> root element.', 'Wrap the artboard content in <x-dc>...</x-dc>.');
  }
  const scriptTags = [...source.matchAll(/<script\b([^>]*)>/g)];
  for (const [, attrs] of scriptTags) {
    if (/src\s*=/.test(attrs) && !/src\s*=\s*"\.\/support\.js"/.test(attrs)) {
      err(
        `An external script is loaded: ${attrs.trim()}`,
        'The canvas has no network egress. Inline the code instead.',
      );
    }
  }

  // --- The logic block ---------------------------------------------------
  // Match on the ATTRIBUTE, not on its position: `<script data-props='...'
  // data-dc-script>` is legal HTML and defeated the old position-anchored
  // regex, so a malformed block validated clean by being written backwards.
  // Every block is checked, not just the first: a second, empty one errors at
  // runtime and used to pass here.
  const dcScripts = [...source.matchAll(/<script\b([^>]*\bdata-dc-script\b[^>]*)>([\s\S]*?)<\/script>/g)];
  if (dcScripts.length > 1) {
    warn(
      `${dcScripts.length} logic blocks. The runtime uses one.`,
      'Merge them into a single `class Component extends DCLogic`.',
    );
  }
  for (const dcScript of dcScripts) {
    const [, attrs, code] = dcScript;
    if (!code.trim()) {
      err('An empty <script data-dc-script> block will error.', 'Omit the script entirely for a static artboard.');
    } else if (!/class\s+Component\s+extends\s+DCLogic/.test(code)) {
      err('The logic block must declare `class Component extends DCLogic`.', null);
    }
    if (/\bimport\b|\bexport\b/.test(code)) {
      err('The logic block is classic script, not a module. import and export will fail.', null);
    }
    if (/\brender\s*\(/.test(code) && !/renderVals/.test(code)) {
      warn('A render() method is not part of the contract.', 'Return template inputs from renderVals() instead.');
    }
    const propsAttr = /data-props\s*=\s*(['"])([\s\S]*?)\1/.exec(attrs);
    if (propsAttr) {
      if (propsAttr[1] !== "'") {
        err('data-props must be single-quoted.', "Write data-props='{...}' so JSON double quotes survive.");
      }
      try {
        decodeProps(propsAttr[2]);
      } catch (e) {
        err(`data-props is not valid JSON after entity decoding: ${e.message}`, null);
      }
    }
  }

  // --- Handlebars holes --------------------------------------------------
  for (const m of source.matchAll(/\{\{([^}]*)\}\}/g)) {
    const inner = m[1].trim();
    const isDotted = /^\$?[A-Za-z_][\w$]*(\.[A-Za-z_$][\w$]*|\.\d+)*$/.test(inner);
    const isLiteral = /^(true|false|null|-?\d+(\.\d+)?|'[^']*'|"[^"]*")$/.test(inner);
    if (!isDotted && !isLiteral) {
      err(
        `{{${inner}}} is not a dotted lookup. Holes cannot contain expressions, and this will render as literal text.`,
        'Compute the value in renderVals() and bind the result.',
      );
    }
  }
  // Ternaries written around a hole are the classic version of the same bug.
  // The shape has to be a WHOLE ternary inside an ATTRIBUTE value: a question
  // mark after a hole is ordinary copy ("Ready to go, {{name}}?") and used to
  // be reported as an error, which blocked publishing on a legitimate headline.
  if (/=\s*"[^"]*\{\{[^}]+\}\}[^"]*\?[^"]*:[^"]*"/.test(source)
    || /=\s*'[^']*\{\{[^}]+\}\}[^']*\?[^']*:[^']*'/.test(source)) {
    err(
      'A ternary sits outside a handlebars hole in an attribute value, so it renders as literal text and the attribute is dropped.',
      'Precompute the branch in renderVals() and bind the result.',
    );
  }

  // --- Images ------------------------------------------------------------
  for (const m of source.matchAll(/<img\b[^>]*>/g)) {
    const tag = m[0];
    const src = /src\s*=\s*("([^"]*)"|'([^']*)'|([^\s>]+))/.exec(tag);
    if (!src) {
      err(`An <img> has no src: ${tag.slice(0, 80)}`, null);
      continue;
    }
    if (!src[2]) {
      err(
        `An image src must be double-quoted for the canvas to substitute it: ${tag.slice(0, 80)}`,
        'Write <img src="logo.png">, not single quotes and not unquoted.',
      );
    }
    const value = src[2] ?? src[3] ?? src[4];
    if (/^data:/.test(value)) {
      err(
        'An image src starts with data:, which double-wraps and renders broken.',
        'Store the image as a bare base64 files entry and reference it by filename.',
      );
    }
    if (/^https?:\/\//.test(value)) {
      err(`An image is loaded from ${value}, but the canvas has no network egress.`, 'Embed it as a files entry.');
    }
    if (!/alt\s*=/.test(tag)) {
      warn(`An image has no alt attribute: ${tag.slice(0, 60)}`, 'Add alt="" for decoration, or a real description.');
    }
  }

  // --- Anything else that tries to reach the network ----------------------
  // The canvas has no egress. Each of these renders as a silent nothing, which
  // is precisely the class of failure this validator exists to make loud.
  // Google Fonts is the one carve-out in the CSP, and it is reachable through
  // @import as well as <link>, so the generic check has to know that or it
  // rejects the only remote resource that actually works.
  const FONT_HOSTS = /^https:\/\/fonts\.(googleapis|gstatic)\.com\//;
  for (const m of source.matchAll(/url\(\s*['"]?(https?:\/\/[^)'"\s]+)/gi)) {
    if (FONT_HOSTS.test(m[1])) continue;
    err(
      `CSS loads ${m[1]}, and the canvas has no network egress.`,
      'Inline it: images as a bare base64 files entry, everything else as literal CSS.',
    );
  }
  for (const m of source.matchAll(/@import\s+(?:url\(\s*)?['"]?(https?:\/\/[^)'"\s;]+)/gi)) {
    if (FONT_HOSTS.test(m[1])) continue;
    err(`An @import reaches ${m[1]}, which the canvas blocks.`, 'Google Fonts is the only permitted host.');
  }
  for (const m of source.matchAll(/<(iframe|video|audio|object|embed|source|track)\b([^>]*)>/gi)) {
    const url = /(?:src|data)\s*=\s*"([^"]*)"/.exec(m[2])?.[1] ?? '';
    if (/^https?:\/\//.test(url)) {
      err(`<${m[1].toLowerCase()}> loads ${url}, and the canvas has no network egress.`, 'Inline the asset, or draw a marked placeholder instead.');
    }
  }

  // --- Fonts and stylesheets ---------------------------------------------
  for (const m of source.matchAll(/<link\b[^>]*>/g)) {
    const tag = m[0];
    const href = /href\s*=\s*"([^"]*)"/.exec(tag)?.[1] ?? '';
    if (/stylesheet/.test(tag) && !/^https:\/\/fonts\.googleapis\.com\//.test(href)) {
      err(
        `A stylesheet is loaded from ${href || 'an unquoted href'}, which the canvas blocks.`,
        'Google Fonts is the only permitted host. Inline everything else.',
      );
    }
    if (!allowFonts && /fonts\.googleapis\.com/.test(href)) {
      warn('A web font is loaded, but PNG and PDF export cannot embed it.', 'Pick a fallback with close metrics.');
    }
  }

  // --- House rules -------------------------------------------------------
  const textOnly = source
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<script[\s\S]*?<\/script>/g, '')
    .replace(/<style[\s\S]*?<\/style>/g, '')
    .replace(/<[^>]+>/g, ' ');
  if (EMOJI_RE.test(textOnly)) {
    warn(
      'The artboard contains emoji.',
      'Draw icons as inline SVG on a 16/20/24px grid. Emoji render differently on every platform and read as a tell.',
    );
  }
  // Everything from here to the flex check used to be a third hand-maintained
  // copy of the anti-slop rules, and it disagreed with guardian.mjs: a comment
  // that stood here recorded the day `font-family: 'Inter', sans-serif` passed
  // one validator and failed the other. There is now one implementation, and it
  // reads references/04-anti-slop.md, which is the document a person edits.
  // Generated sheets are exempt, for the same reason `check` exempts them: the
  // components sheet demonstrates the whole radius scale and the palette sheet
  // numbers twelve ramp steps, so holding either to a rule about restraint is
  // faulting a specimen for containing specimens.
  if (!source.slice(0, 4096).includes(GENERATED_MARKER)) {
    for (const f of slopFindings(loadContractSync(), source, { name })) {
      (f.severity === 'p0' ? err : warn)(f.message, f.fix);
    }
  }

  // --- Layout craft ------------------------------------------------------
  // Kept here rather than in the contract because it needs two facts at once,
  // and a regex that spans a whole document to correlate them is a regex that
  // will eventually match something innocent. Sometimes there really are three
  // things and they really are ordered, so it warns rather than fails.
  const threeCol = /grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/.test(source);
  const sequenceNumbering = /(^|>)\s*0?1\s*<[\s\S]{0,600}?(^|>)\s*0?2\s*<[\s\S]{0,600}?(^|>)\s*0?3\s*</m.test(source);
  if (threeCol && sequenceNumbering) {
    warn(
      'A three-column grid numbered 01 / 02 / 03. This is the most-generated section on the internet, and the numbering claims a sequence.',
      'Keep it only if the content genuinely is ordered steps. Otherwise try a single-column editorial run, a comparison, or one full-bleed demonstration.',
    );
  }

  const flexCount = (source.match(/display:\s*(flex|grid)/g) ?? []).length;
  const gapCount = (source.match(/\bgap:/g) ?? []).length;
  if (flexCount > 0 && gapCount === 0) {
    warn(
      'Flex or grid containers with no gap.',
      'Space siblings with gap, not margins: gap survives the canvas editor reordering, deleting and duplicating elements.',
    );
  }

  return { name, ok: errors.length === 0, errors, warnings };
}

/** Validate a whole set at once, plus the manifest that lays them out. */
export function validateCanvas({ artboards, manifest }) {
  const results = artboards.map(({ file, source }) =>
    validateArtboard(source, { name: file }),
  );
  const errors = results.flatMap((r) => r.errors.map((e) => ({ file: r.name, ...e })));
  const warnings = results.flatMap((r) => r.warnings.map((w) => ({ file: r.name, ...w })));

  // Checked whether or not a manifest exists: the Territories round publishes a
  // freshly written folder with no manifest yet, which is exactly when a missing
  // Main bites, and the old placement inside the manifest branch meant the
  // warning never fired there.
  if (!artboards.some((a) => a.file === 'Main.dc.html')) {
    warnings.push({
      file: 'Main.dc.html',
      message: 'No Main artboard. The seeder warns about this and falls back to the first artboard alphabetically as the entry.',
      fix: 'Name the leading deliverable Main.dc.html so the entry artboard is a decision. During a direction round, Main is the contents page.',
    });
  }

  if (manifest) {
    const files = new Set(artboards.map((a) => a.file));
    for (const b of manifest.artboards) {
      if (!files.has(b.file)) errors.push({ file: b.file, message: 'Listed in canvas.json but not written to disk.', fix: null });
    }
    for (const f of files) {
      if (!manifest.artboards.some((b) => b.file === f)) {
        warnings.push({ file: f, message: 'On disk but not in canvas.json, so it will be appended in an arbitrary slot.', fix: 'Give it a deliberate position.' });
      }
    }
    for (const b of manifest.artboards) {
      for (const k of ['x', 'y', 'w', 'h']) {
        if (typeof b[k] !== 'number' || !Number.isFinite(b[k])) {
          errors.push({ file: b.file, message: `${k} is ${JSON.stringify(b[k])}, which the seeder cannot lay out.`, fix: 'Rebuild the manifest with canvasManifest, which refuses non-finite geometry.' });
        }
      }
    }
    for (const clash of findOverlaps(manifest)) {
      errors.push({ file: clash.a, message: `Overlaps ${clash.b}, including the name strip above each frame.`, fix: 'Leave at least 80px between frames in a row and 120px between rows.' });
    }
    for (const tight of findCrowding(manifest)) {
      warnings.push({
        file: tight.a,
        message: `Only ${tight.gap}px from ${tight.b} on the ${tight.axis} axis, where the canvas chrome wants ${tight.min}px.`,
        fix: 'The frames will render, but their titles and tweak chips will crowd each other.',
      });
    }
  }

  return { ok: errors.length === 0, errors, warnings };
}

export default {
  artboard, canvasManifest, validateArtboard, validateCanvas, findOverlaps, findCrowding,
  encodeProps, decodeProps, FRAMES, BANNED_FONTS, DEFAULT_FONTS,
};
