/**
 * Brandi token emitters.
 *
 * One resolved design system in, four artefacts out:
 *   tokens.json    Design Tokens Community Group (DTCG) format
 *   tokens.css     custom properties, three tiers, light and dark
 *   tailwind.css   a Tailwind v4 @theme block
 *   tokens.ts      a typed TypeScript module
 *
 * DTCG is a Design Tokens Community Group Report, NOT a W3C standard and not on
 * the W3C Standards Track. The current draft (Format Module 2025.10) carries the
 * line "Do not attempt to implement this version." So this emitter targets the
 * shape the ecosystem actually reads, states every divergence in
 * references/10-implementation.md, and calls the output DTCG rather than
 * implying a standard that does not exist.
 * https://tr.designtokens.org/format/
 *
 * The format has also changed shape: `dimension` was a string
 * ("16px") in early drafts and became an object ({value: 16, unit: "px"}) in
 * the 2024 revision. Style Dictionary and most tooling in the wild still read
 * the string form, so `dimensionStyle` lets a caller pick. The default follows
 * the current spec; pass 'string' when feeding an older pipeline.
 * https://tr.designtokens.org/format/
 */

import { resolveToken } from './system.mjs';

const DTCG_SCHEMA = 'https://tr.designtokens.org/format/';
const DTCG_STATUS =
  'Design Tokens Community Group Report format. This is a Community Group Report, ' +
  'not a W3C standard, and the draft is still changing. Check what your build tool ' +
  'actually reads before wiring this in.';

function dim(px, style) {
  if (style === 'string') return `${px}px`;
  return { value: px, unit: 'px' };
}

/** Escape a string for safe inclusion in a CSS comment. */
const cssComment = (s) => String(s).replace(/\*\//g, '*\\/');

/** A CSS custom property name from a dotted token path. */
export const cssVar = (path) => `--${path.replace(/\./g, '-')}`;

// ---------------------------------------------------------------------------
// DTCG
// ---------------------------------------------------------------------------

/**
 * Emit DTCG tokens.
 *
 * Structure follows the three tiers. Tier 1 lives under `color`, `space`,
 * `radius`, `font`, `duration` and so on. Tier 2 lives under `semantic`, and
 * every entry there is an alias, which is what makes theming a swap rather
 * than a rewrite. Dark mode is emitted as a sibling `semantic-dark` group
 * rather than a `$extensions` block, because the spec has no theming primitive
 * yet and a sibling group is the shape every build tool already understands.
 */
export function toDtcg(system, { dimensionStyle = 'object', includeDark = true, letterSpacingUnit = 'em' } = {}) {
  if (!['em', 'rem'].includes(letterSpacingUnit)) {
    throw new TypeError(`letterSpacingUnit must be "em" or "rem", got ${letterSpacingUnit}`);
  }
  const out = {
    $schema: DTCG_SCHEMA,
    $description:
      DTCG_STATUS + ' ' +
      'Design tokens generated by Brandi. Tier 1 (color, space, radius, font, ' +
      'duration, easing, shadow) holds primitives and never changes between themes. ' +
      'Tier 2 (semantic) holds aliases and is the only tier a theme swaps. ' +
      'Consume tier 2. Reaching past it into tier 1 is how a design system dies.',
  };

  // --- Tier 1: colour ----------------------------------------------------
  const color = { $type: 'color' };
  const families = { ...system.palettes, ...system.status };
  for (const [family, pal] of Object.entries(families)) {
    const group = {
      $description: `${family} ramp. Step 9 is the colour itself; 1-8 are surfaces and borders, 11-12 are text.`,
    };
    pal.light.steps.forEach((s) => {
      group[String(s.step)] = {
        $value: s.hex,
        $description: `${s.role}: ${s.use}`,
      };
    });
    if (includeDark) {
      const darkGroup = { $description: `${family} ramp, dark theme.` };
      pal.dark.steps.forEach((s) => {
        darkGroup[String(s.step)] = { $value: s.hex, $description: `${s.role}: ${s.use}` };
      });
      color[`${family}-dark`] = darkGroup;
    }
    color[family] = group;
  }
  out.color = color;

  // --- Tier 1: dimension -------------------------------------------------
  out.space = { $type: 'dimension', $description: 'Spacing scale, named by pixel value.' };
  for (const s of system.space) out.space[s.name] = { $value: dim(s.px, dimensionStyle) };

  out.radius = { $type: 'dimension', $description: `Corner radius. Stance: ${system.meta.shape}.` };
  for (const r of system.radius) out.radius[r.name] = { $value: dim(r.px, dimensionStyle) };

  out.breakpoint = { $type: 'dimension', $description: system.layout.note };
  for (const b of system.layout.breakpoints) out.breakpoint[b.name] = { $value: dim(b.px, dimensionStyle), $description: b.use };

  out.layout = { $type: 'dimension', $description: 'Content column and gutter, derived from the measure.' };
  out.layout['content-max'] = { $value: dim(system.layout.contentMaxPx, dimensionStyle), $description: 'The widest a single text column should ever be.' };
  out.layout.gutter = { $value: dim(system.layout.gutterPx, dimensionStyle) };

  // --- Tier 1: typography ------------------------------------------------
  out.font = {
    family: {
      $type: 'fontFamily',
      ...Object.fromEntries(
        Object.entries(system.type.fonts)
          .filter(([, v]) => v)
          .map(([role, family]) => [role, { $value: Array.isArray(family) ? family : [family] }]),
      ),
    },
    size: {
      $type: 'dimension',
      ...Object.fromEntries(system.type.scale.steps.map((s) => [s.name, { $value: dim(s.px, dimensionStyle), $description: s.use }])),
    },
    lineHeight: {
      $type: 'number',
      ...Object.fromEntries(system.type.scale.steps.map((s) => [s.name, { $value: s.lineHeight }])),
    },
    letterSpacing: {
      $type: 'dimension',
      // The DTCG dimension type permits px and rem only, and letter spacing
      // belongs in em: it has to scale with the size it is applied to, which is
      // the whole point of tracking. `em` is therefore the default and a strict
      // validator will flag it. `rem` converts at the step's own minimum size,
      // which is exact for a fixed scale and an approximation for a fluid one,
      // and that trade is stated in the token's description rather than hidden.
      ...Object.fromEntries(
        system.type.scale.steps.map((s) => {
          const em = Number(s.letterSpacing.replace('em', ''));
          if (letterSpacingUnit === 'rem') {
            const rem = Number(((em * s.px) / system.type.scale.rootPx).toFixed(5));
            return [s.name, {
              $value: dimensionStyle === 'string' ? `${rem}rem` : { value: rem, unit: 'rem' },
              $description: `Converted from ${s.letterSpacing} at ${s.px}px for spec conformance. Exact at that size only; use the em value for a fluid scale.`,
            }];
          }
          return [s.name, {
            $value: dimensionStyle === 'string' ? s.letterSpacing : { value: em, unit: 'em' },
          }];
        }),
      ),
    },
  };

  // Composite typography tokens: one token per step, ready to apply whole.
  out.typography = { $type: 'typography' };
  const bodyRef = system.type.fonts.body ? '{font.family.body}' : null;
  for (const s of system.type.scale.steps) {
    out.typography[s.name] = {
      $value: {
        ...(bodyRef ? { fontFamily: bodyRef } : {}),
        fontSize: `{font.size.${s.name}}`,
        lineHeight: `{font.lineHeight.${s.name}}`,
        letterSpacing: `{font.letterSpacing.${s.name}}`,
      },
      $description: s.use,
    };
  }

  out.chart = { $type: 'color', $description: system.dataViz.note };
  system.dataViz.categorical.forEach((hex, i) => { out.chart[`categorical-${i + 1}`] = { $value: hex }; });
  system.dataViz.sequential.forEach((hex, i) => { out.chart[`sequential-${i + 1}`] = { $value: hex }; });

  out.fontWeight = { $type: 'fontWeight', $description: 'The three weights the font request downloads. A weight that is not loaded is a weight the browser fakes.' };
  for (const w of system.type.weights) out.fontWeight[w.name] = { $value: w.value, $description: w.use };

  // --- Tier 1: motion and elevation --------------------------------------
  out.duration = { $type: 'duration' };
  for (const d of system.motion.durations) {
    out.duration[d.name] = {
      $value: dimensionStyle === 'string' ? `${d.ms}ms` : { value: d.ms, unit: 'ms' },
      $description: d.use,
    };
  }
  out.easing = { $type: 'cubicBezier' };
  for (const [name, e] of Object.entries(system.motion.easings)) {
    const nums = e.value.match(/-?[\d.]+/g).map(Number);
    out.easing[name] = { $value: nums, $description: e.use };
  }

  out.shadow = { $type: 'shadow', $description: 'Elevation. Tinted with the brand hue, never pure black.' };
  for (const e of system.elevation) {
    // The spec's shadow type is a structured object; these are authored as CSS
    // strings because they are multi-layer and hue-tinted. Kept as a string
    // with an explicit type override so tooling does not mis-parse them.
    out.shadow[e.name] = { $type: 'string', $value: e.value, $description: e.use };
  }

  // --- Tier 2: semantic --------------------------------------------------
  const toGroup = (flat) => {
    const g = {};
    for (const [key, value] of Object.entries(flat)) {
      const [head, ...rest] = key.split('.');
      g[head] ??= { $type: 'color' };
      g[head][rest.join('.')] = { $value: value };
    }
    return g;
  };
  out.semantic = { $description: 'Tier 2. Consume these. Aliases resolve into tier 1.', ...toGroup(system.semantic.light) };
  if (includeDark) {
    const darkFlat = Object.fromEntries(
      Object.entries(system.semantic.dark).map(([k, v]) => [k, typeof v === 'string' && v.startsWith('{') ? v.replace('{color.', '{color.').replace(/^\{color\.([a-z0-9]+)\./i, '{color.$1-dark.') : v]),
    );
    out['semantic-dark'] = { $description: 'Tier 2, dark theme. Same keys, different primitives.', ...toGroup(darkFlat) };
  }

  return out;
}

// ---------------------------------------------------------------------------
// CSS
// ---------------------------------------------------------------------------

/**
 * Emit CSS custom properties.
 *
 * Light and dark are genuinely different scales, not the same colours
 * rearranged: a dark surface is not an inverted light one, and the chroma that
 * reads as confident on white reads as radioactive on near-black. So the
 * primitive ramps are re-declared per theme, the way Radix Colors does it,
 * rather than duplicated into `-light` and `-dark` names. The semantic layer is
 * declared per theme too, which is what lets a role point at a DIFFERENT step
 * in each theme (a raised surface sits on step 1 in light and step 2 in dark).
 *
 * The tier boundary is still the load-bearing part: components consume semantic
 * tokens and never learn which theme is active.
 */
export function toCss(system, {
  prefix = '',
  darkSelector = '[data-theme="dark"]',
  includeSystemPreference = true,
  colorFormat = 'hex',
} = {}) {
  const p = prefix ? `${prefix}-` : '';
  const L = [];
  const val = (step) => (colorFormat === 'oklch' ? step.oklch : step.hex);
  const families = { ...system.palettes, ...system.status };

  L.push('/*');
  L.push(' * Design tokens. Generated by Brandi. Edit the brand file, not this.');
  L.push(' *');
  L.push(' * Three layers:');
  L.push(' *   :root primitives   raw values. Identical in every theme. Do not consume directly.');
  L.push(' *   :root semantic     what a value is FOR. Consume these.');
  L.push(' *   dark selector     the same semantic keys pointing at different primitives.');
  L.push(' *');
  L.push(' * If you find yourself writing var(--color-brand-9) in a component, the');
  L.push(' * semantic layer is missing a token. Add one there instead.');
  L.push(' */');
  L.push('');

  const primitives = (mode, indent) => {
    const out = [];
    out.push(`${indent}/* Colour ramps */`);
    for (const [family, pal] of Object.entries(families)) {
      for (const st of pal[mode].steps) {
        out.push(`${indent}--${p}color-${family}-${st.step}: ${val(st)}; /* ${cssComment(st.role)} */`);
      }
    }
    return out;
  };

  const semanticBlock = (flat, indent) =>
    Object.entries(flat).map(([key, value]) => {
      const resolved = typeof value === 'string' && value.startsWith('{')
        ? `var(--${p}color-${value.slice(1, -1).split('.').slice(1).join('-')})`
        : value;
      return `${indent}--${p}${key.replace(/\./g, '-')}: ${resolved};`;
    });

  // --- Light: primitives, then the semantic layer over them --------------
  L.push(':root {');
  L.push('  color-scheme: light;');
  L.push(...primitives('light', '  '));
  L.push('');
  L.push('  /* Spacing */');
  for (const st of system.space) L.push(`  --${p}space-${st.name}: ${st.px === 0 ? '0' : `${st.rem}rem`};`);
  L.push('');
  L.push('  /* Radius */');
  for (const r of system.radius) L.push(`  --${p}radius-${r.name}: ${r.px === 9999 ? '9999px' : `${r.px}px`};`);
  L.push('');
  L.push('  /* Chart colour. Not the brand ramps: those are built for hierarchy,');
  L.push('     these are checked to stay apart under colour-blindness. */');
  system.dataViz.categorical.forEach((hex, i) => L.push(`  --${p}chart-${i + 1}: ${hex};`));
  system.dataViz.sequential.forEach((hex, i) => L.push(`  --${p}chart-seq-${i + 1}: ${hex};`));
  L.push('');
  L.push('  /* Layout. A custom property cannot be used inside a media query, so');
  L.push('     these are the numbers to type into one, not values to reference');
  L.push('     there. --content-max IS usable, and is what a text column wants. */');
  for (const b of system.layout.breakpoints) L.push(`  --${p}bp-${b.name}: ${b.px}px;  /* ${b.use} */`);
  L.push(`  --${p}content-max: ${system.layout.contentMaxPx}px;`);
  L.push(`  --${p}gutter: ${system.layout.gutterPx}px;`);
  L.push('');
  L.push('  /* Type */');
  for (const w of system.type.weights) L.push(`  --${p}font-weight-${w.name}: ${w.value};  /* ${w.use} */`);
  for (const [role, family] of Object.entries(system.type.fonts)) {
    if (family) L.push(`  --${p}font-${role}: ${Array.isArray(family) ? family.join(', ') : family};`);
  }
  for (const st of system.type.scale.steps) {
    L.push(`  --${p}text-${st.name}: ${st.clamp ?? `${st.rem}rem`};`);
    L.push(`  --${p}leading-${st.name}: ${st.lineHeight};`);
    L.push(`  --${p}tracking-${st.name}: ${st.letterSpacing};`);
  }
  L.push(`  --${p}measure: ${system.type.measure.css};`);
  L.push('');
  L.push('  /* Elevation */');
  for (const e of system.elevation) L.push(`  --${p}shadow-${e.name}: ${e.value};`);
  L.push('');
  L.push('  /* Focus */');
  L.push(`  --${p}focus-ring-width: ${system.focus.widthPx}px;`);
  L.push(`  --${p}focus-ring-offset: ${system.focus.offsetPx}px;`);
  L.push('');
  L.push('  /* Motion */');
  for (const d of system.motion.durations) L.push(`  --${p}duration-${d.name}: ${d.ms}ms;`);
  for (const [name, e] of Object.entries(system.motion.easings)) L.push(`  --${p}ease-${name}: ${e.value};`);
  L.push('');
  L.push('  /* Tier 2. These are the tokens components use. */');
  L.push(...semanticBlock(system.semantic.light, '  '));
  L.push('}');
  L.push('');

  // --- Dark: the same keys, re-pointed -----------------------------------
  const darkBody = (indent) => [
    `${indent}color-scheme: dark;`,
    ...primitives('dark', indent),
    '',
    `${indent}/* Tier 2, dark. Same keys. Some point at a different step on purpose. */`,
    ...semanticBlock(system.semantic.dark, indent),
  ];

  L.push(`${darkSelector} {`);
  L.push(...darkBody('  '));
  L.push('}');
  L.push('');

  if (includeSystemPreference) {
    L.push('/* Readers who have expressed a preference but not toggled anything. */');
    L.push('@media (prefers-color-scheme: dark) {');
    L.push('  :root:not([data-theme="light"]) {');
    L.push(...darkBody('    '));
    L.push('  }');
    L.push('}');
    L.push('');
  }

  L.push('/* Honour the reader\'s setting rather than overriding it. WCAG 2.2 2.3.3 is');
  L.push('   Level AAA, so this is a house rule rather than an AA requirement, and it is');
  L.push('   one worth keeping. */');
  L.push('@media (prefers-reduced-motion: reduce) {');
  L.push('  *, *::before, *::after {');
  L.push('    animation-duration: 0.01ms !important;');
  L.push('    animation-iteration-count: 1 !important;');
  L.push('    transition-duration: 0.01ms !important;');
  L.push('    scroll-behavior: auto !important;');
  L.push('  }');
  L.push('}');
  L.push('');
  L.push('/* A focus indicator that is actually visible: WCAG 2.2 2.4.7 Focus Visible,');
  L.push('   at the 3:1 contrast 1.4.11 Non-text Contrast requires. (2.4.11 is Focus');
  L.push('   Not Obscured, which is a different thing.) */');
  L.push(':where(a, button, input, select, textarea, summary, [tabindex]):focus-visible {');
  L.push(`  outline: var(--${p}focus-ring-width) solid var(--${p}focus-ring);`);
  L.push(`  outline-offset: var(--${p}focus-ring-offset);`);
  L.push('}');
  L.push('');

  return L.join('\n');
}

// ---------------------------------------------------------------------------
// Tailwind v4
// ---------------------------------------------------------------------------

/**
 * A Tailwind v4 `@theme` block. v4 reads design tokens straight from CSS custom
 * properties inside `@theme`, so there is no JS config to keep in sync.
 * https://tailwindcss.com/docs/theme
 */
export function toTailwind(system, { importTokens = './tokens.css' } = {}) {
  const L = [];
  L.push('/* Tailwind v4 theme, generated by Brandi. Edit the brand file, not this. */');
  L.push('/*');
  L.push(' * Every entry below resolves through tokens.css, which is imported first, so');
  L.push(' * a Tailwind utility and a hand-written rule always land on the same value.');
  L.push(' * The names are namespaced (--color-*, --text-*, --spacing-*) because that is');
  L.push(' * what Tailwind reads; the underlying custom properties keep their own names,');
  L.push(' * so nothing here is self-referential and import order does not matter.');
  L.push(' */');
  if (importTokens) L.push(`@import "${importTokens}";`);
  L.push('@import "tailwindcss";');
  L.push('');
  L.push('@theme {');
  L.push('  /* Semantic colours. These are the ones to use: bg-surface-page, text-text-primary. */');
  for (const key of Object.keys(system.semantic.light)) {
    const name = key.replace(/\./g, '-');
    L.push(`  --color-${name}: var(--${name});`);
  }
  L.push('');
  L.push('  /* Ramps, for the rare case a semantic token genuinely does not exist yet. */');
  for (const [family, pal] of Object.entries({ ...system.palettes, ...system.status })) {
    // Already namespaced --color-* in tokens.css, so these would be self-referential.
    // Emitted as literals instead, which is also what makes them theme-stable:
    // a utility built from a ramp step means that step, not "whatever the theme says".
    for (const s of pal.light.steps) L.push(`  --color-${family}-${s.step}: ${s.hex};`);
  }
  L.push('');
  L.push('  /* Type. The custom properties in tokens.css are --text-* and --font-*,');
  L.push('     which is the same namespace Tailwind uses, so these carry the values. */');
  for (const s of system.type.scale.steps) L.push(`  --text-${s.name}: ${s.clamp ?? `${s.rem}rem`};`);
  for (const [role, family] of Object.entries(system.type.fonts)) {
    if (family) L.push(`  --font-${role}: ${Array.isArray(family) ? family.join(', ') : family};`);
  }
  L.push('');
  L.push('  /* Space. tokens.css calls these --space-*, Tailwind wants --spacing-*,');
  L.push('     so this is a genuine alias rather than a self-reference. */');
  for (const s of system.space) L.push(`  --spacing-${s.name}: var(--space-${s.name});`);
  L.push('');
  L.push('  /* Radius and elevation share their namespace with tokens.css, so they carry values. */');
  for (const r of system.radius) L.push(`  --radius-${r.name}: ${r.px === 9999 ? '9999px' : `${r.px}px`};`);
  L.push('');
  for (const e of system.elevation) L.push(`  --shadow-${e.name}: ${e.value};`);
  L.push('');
  L.push('  /* Weights, the same three the font request actually downloads. */');
  for (const w of system.type.weights) L.push(`  --font-weight-${w.name}: ${w.value};`);
  L.push('');
  L.push('  /* Tailwind v4 builds its responsive variants from --breakpoint-*. */');
  for (const b of system.layout.breakpoints) L.push(`  --breakpoint-${b.name}: ${b.px}px;`);
  L.push('}');
  L.push('');
  return L.join('\n');
}

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------

/** A typed module, for anything that needs token values in JS rather than CSS. */
export function toTypeScript(system) {
  const semantic = Object.fromEntries(
    Object.entries(system.semantic.light).map(([k, v]) => [k, resolveToken(v, system, 'light')]),
  );
  const semanticDark = Object.fromEntries(
    Object.entries(system.semantic.dark).map(([k, v]) => [k, resolveToken(v, system, 'dark')]),
  );
  const body = {
    color: Object.fromEntries(
      Object.entries({ ...system.palettes, ...system.status }).map(([f, pal]) => [
        f,
        {
          light: Object.fromEntries(pal.light.steps.map((s) => [s.step, s.hex])),
          dark: Object.fromEntries(pal.dark.steps.map((s) => [s.step, s.hex])),
        },
      ]),
    ),
    semantic: { light: semantic, dark: semanticDark },
    space: Object.fromEntries(system.space.map((s) => [s.name, s.px])),
    radius: Object.fromEntries(system.radius.map((r) => [r.name, r.px])),
    text: Object.fromEntries(system.type.scale.steps.map((s) => [s.name, { size: s.clamp ?? `${s.rem}rem`, lineHeight: s.lineHeight, letterSpacing: s.letterSpacing }])),
    font: system.type.fonts,
    fontWeight: Object.fromEntries(system.type.weights.map((w) => [w.name, w.value])),
    shadow: Object.fromEntries(system.elevation.map((e) => [e.name, e.value])),
    chart: { categorical: system.dataViz.categorical, sequential: system.dataViz.sequential },
    // Print is deliberately not a CSS token: there is no CSS meaning for a
    // Pantone. It rides in the machine formats so a print vendor can be sent
    // one file, and it is set out properly in the book.
    print: system.print.swatches.map((w) => ({
      role: w.role, hex: w.hex, cmyk: w.cmykString, computed: w.computed,
      pantoneCoated: w.pantoneCoated, ral: w.ral, verified: w.verified,
    })),
    breakpoint: Object.fromEntries(system.layout.breakpoints.map((b) => [b.name, b.px])),
    layout: { contentMax: system.layout.contentMaxPx, gutter: system.layout.gutterPx },
    duration: Object.fromEntries(system.motion.durations.map((d) => [d.name, d.ms])),
    easing: Object.fromEntries(Object.entries(system.motion.easings).map(([k, v]) => [k, v.value])),
  };
  return [
    '// Design tokens. Generated by Brandi. Edit the brand file, not this.',
    '// Prefer the CSS custom properties where you can: they theme without a re-render.',
    '',
    `export const tokens = ${JSON.stringify(body, null, 2)} as const;`,
    '',
    'export type Tokens = typeof tokens;',
    "export type SemanticToken = keyof Tokens['semantic']['light'];",
    'export default tokens;',
    '',
  ].join('\n');
}

export default { toDtcg, toCss, toTailwind, toTypeScript, cssVar };
